language: go
go:
    - 1.9.x
    - 1.10.x

install:
    - mkdir -p /tmp/bin
    - wget -O /tmp/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    - chmod 755 /tmp/bin/jq
    - wget -O /tmp/bin/yaml "https://github.com/mikefarah/yq/releases/download/1.13.1/yaml_linux_amd64"
    - chmod 755 /tmp/bin/yaml
    - export PATH=$PATH:/tmp/bin/
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/mattn/goveralls
    - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/bin/cc-test-reporter
  - chmod +x /tmp/bin/cc-test-reporter
  - cc-test-reporter before-build

script:
  - make local cover

after_script:
  - cp cover/cover.out c.out
  - cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
