FROM golang:1.18

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
        zip \
    && rm -rf /var/lib/apt/lists/*

ENV YAML_BIN_VERSION 1.13.1
ENV JQ_BIN_VERSION 1.6

RUN wget -O /usr/local/bin/jq "https://github.com/stedolan/jq/releases/download/jq-${JQ_BIN_VERSION}/jq-linux64" \
    && chmod 755 /usr/local/bin/jq \
    && wget -O /usr/local/bin/yaml "https://github.com/mikefarah/yq/releases/download/${YAML_BIN_VERSION}/yaml_linux_amd64" \
    && chmod 755 /usr/local/bin/yaml

RUN go install golang.org/x/tools/cmd/goimports@latest \
    && go install github.com/mattn/goveralls@latest \
    && go install github.com/mitchellh/gox@latest \
    && go install github.com/x-motemen/gobump/cmd/gobump@latest \
    && go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest \
    && go install github.com/tcnksm/ghr@latest \
    && wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh

ENV CGO_ENABLED 0
